creation_rules:
  - path_regex: clusters/eks/.*\.yaml$
    age: age1m7uketvs2yftsh43p7w2eq2cqxsm9eac3xazmg6d38nrkka4la2qkjyjk6
  - path_regex: clusters/gke/.*\.yaml$
    age: age1m7uketvs2yftsh43p7w2eq2cqxsm9eac3xazmg6d38nrkka4la2qkjyjk6
