apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: pdvd
  namespace: flux-system

resources:
  - pdvd-helmrepository.yaml
  - pdvd-helmrelease.yaml
  - secrets.enc.yaml           

configMapGenerator:
  - name: pdvd-values
    namespace: flux-system
    files:
      - values.yaml

# Remove the secretGenerator block entirely
generatorOptions:
  disableNameSuffixHash: true