apiVersion: v1
kind: Secret
metadata:
    name: pdvd-secrets
    namespace: flux-system
stringData:
    values.yaml: ENC[AES256_GCM,data:9/YgAb685Hspk6Z/zJtfEHTp7uWHW+8DOy5SCStPu2DUFLuwmq9f6lfwaisA7EC+MURILcMy2puYBtioFaLTZYy3MYK6ZO9qR+tjgCShuFs2GEqtMLCGMNzqKu8m9jkAQIgk6wWSzhzPRuhI21+23VwyN01BlsN2LH/ufsOFhcjZT0ZvgCCfhNrUZRUvwXj+fcvSepEpkdozsw7Q/HsCsgNc5nlPNSmv/B4Nsts6YqBqNgDByeVRobgTd187FqMqFW4X2EvLGLn4rxHGld49oQ/oPH5xG0N1A/OkRW1/GRAU5XG0+qt3weTWjXjdXtLI7UNMphvOZnEq7dj0kiPedJnoLaeww5kBOh+mhA7ndjxGa42ndj8T6w1UH6pVtvNYe7pXfp0lcUc3Ac1oYDe/gT4vXCrgy4PgjSgiBpo0cKixWdP7Jfvs/ojCgvrHVl6jtOdp1wC8pmd5cGLA4sgj4/pa5mieUpIZhNDsd/is8JC2tMqmHxkIAoE72iqUcPo1IFYCd+CsEk8Ld7z6ogjkvw1GaTSXB/maKfuJG4e7F7XJa0JYxNkrODs41cZQtJgoYXu0IrJI+h3TW+g0UcRreE9Bxvaap4kZcb66sfw3r1GVJTbAj3tfML6g66i3OeXoIkeXNIhHBjxYH4Mugq/S37b0w6j3pA0wsFdGDZJPzBjJNZhlkgXimZqH0WPk4ummdQClROCQsSXfLgeo7Uq9MxqmesG1hGP0CfMx0BXJfGkrI1OAzswBZIzDsKu5uEB4JAAhs8KdHNo1tQYkO4gsKtBHiO/kTC/KZ3c4Xzgt/aqEtVfM++2j47q3QGDlXINx7Cq5ZH66eJ8RuADbBeA2Yx7Gtu9zZ1lxWkPLGNCegHB8XeSsT90gt66g3rlNkFlolE/9KWMjHNSsam4pQsfX4EptDskmwTmqb0UNwS+WX1vcX9YXxBZJbcofnBCkpm9ojvF22MrmeVjo6sWr7j/S1kmjhtnrGXvF56fcrmSTFSTwalKlAd0hPzjvA3MEXdRAQjQpNotp0tKsiGFUpiHeR1dtLvMTVDbkatSbYE+K/lus90Hl0zgQOOvRuubHaoes69GlI3DB2yOrRAoy3UhSB1ohddwZ5MxVpboQDxqyXfoVKycKhcTy594KcT0oX2NNhhiwhu5nzo+XVT+zgdZ092CtS2M7Beej24dMeKr5NXiSthumQwFDBy6/hLXrWFlNZi3CY+XeoOMFy0tPv7NcebcOq8nn6vFkWuSTySnWcLLxdL2mOrpOEGuPbTARQU4TGtElTzbihJG5PDcsIzsOCRHTuvIjy4tfmB+/PAd3vxNOf6NCI7Z7poCesGnwsqGpsIsTMX35SqvJH0gNwf5cjzBz5Qh+dOAdtmEOdvM4WN9evEn1kB6ZwWf6CYJcwkPlTwoUNO6azdIINf38qdlv8X8x/N4FafsEIvGRlnQhkRq9ooR8lHHhxLjrkk1IB0oo7uWWGIq/i0QDhCrP2vQNy5w0CGjar9sekLPPFW82WcrFky13A67ClxgK2EX8Cwe/K09yud1zfv/fI2fdI+6hI1+yLoyfTU71aYTZNxpSKMmsCqqTjLSnFe0ROQtspmUkQ4DKAviA8rvoxP6h5gGvlji0afEQxPCYkKI8O5L2ROh2Nu3q7/TugqDXron/VDbeB8EIfWb4TzinLDnsm6EvL4uT5JID5UQD4LcnOor/yhCqLAblkx2F9gLq9Z9Mu+gXEMv4y5AfYHIDlpSK6QKCfD66ybf/NZm6JxPOerX52iejsbBZp8Ny3qG71GK02i+t1UT9El5kX+jPZaZC2v3otaqWIZz/wpkEuVf4QvgwhsKzO2nD8gMBk0nPn9G0b3SShmwhja14/SZ4FiMkLsH9MQwzy6gcTJ+CwLcZGfOAb68bwMwnS3q3ehtlpn4iDTuywFaBqS0D9gXEiE1wPL+3Ax4R6/cXhPMTrgXKNlkxqBTfHB7E+Z//5+oSkBc5baZa8WIq0H/sFHAIdNCe0++Gzic3o7P+W+4+LsTyZZw/BbedOIw75TJgD93JyBV8NFysTqB2LTTKcqRhie+ZNFuJvLxf/Es5BWOIkPmHzphW6hrUDkcpsAiZmehvLawgnDRXxB/ha7Ivstkx1M9XTUbi+pEWhkH5BQB55LZ6Rdrazl6IBHGAeNOWUwszTmUAwYCfANiymNSziLiLuXVNjRk19CBjAl3C9WOeXtGXZwE3NGwV+FSS2FzxH8keIuPSX9hh+q3RYjnujbbvRxhLjVOH+k+6E68m9nVVauCQnUqDxquOB0DtEmb/Smu59PdBdJOXGuXKfQrn/VeI2Vp2cwT8hfNokiD64UBXVRQgvc9y6OzDeEM6fxfXdQ6h7XsIZK0p2Av7JIFLEwB/nH25mfy3Auae4DFHZDEGSmdYtsedkWM+iu5VXTmP5NP2rI/FmaqEXOx1/pDGUyc9djVPD+5JKSKs932ItIGi/uF1ESn/gwAzC8bw8iEyI79HLnCvmQ5d2S7xpSFzSkzYNSmmWwmGxQ7r4HQh1MLPq61QqZsft/YMazRK8h+YCyxvvbjSbvScY9w9TVZHI34GTgadeCnkkk4obWWRyIR/CViQyT6cm448Sv7e4mZMJNtGwGv2V62rOUGU4a3m3ICtiPC7CPLfANtlmFlh6arpGqBMUIPHS1G6Wu+fJdgw4JDyQ34UDwexotNvaGFJgVzW8kxoH9bamy6ltBrPLtDFiZ47nhuP820V6vVZhtxM/IFuxJGXdfXGG9XHrkXLsVvz6Azgxi6RWhPMN5GUpJnqaz0k0xEoVx5baNiKfPYg/XXbaZdr5/nSdCDhVYJXdk8G5mgyk2QZYhDeq3XLtCTwFAsOp3VONYl7xVWy5F7Hs0sIPAqKjgFB+1YdDDM/nm1IeZN2xHKB3xMMGIBUuT+O5eB36eIwxKS9j8GjR5QEpolFEo/ErW4+,iv:GvI1tVyAChlnMbFBRrvbTW+FkrZrSdgTFKIQv5F8/XY=,tag:NfuOtc+7JOrdpc9w61iZWw==,type:str]
sops:
    age:
        - recipient: age1m7uketvs2yftsh43p7w2eq2cqxsm9eac3xazmg6d38nrkka4la2qkjyjk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMDRrcWR2SkNXTXZrQnVX
            aWxRVnMwRVk1cTFFbGdLUC9UQk5oOVhXNDJZCnF5NmNkZUpxN0xRMzltNm5CckVM
            SU1VSnhWVkZrZjBhdHh6b2FKcVJwNjgKLS0tIFJrKzM2a1hnVnZvZDdUbEZlaE9Q
            UEhrTk10aFp2YTVqNUpRcFpDZE9ac3MK5CM0XLoOFFA/oiqKxA7ZsJh61PZd8y6f
            y6PrDZQlswNCAV6wUQL3DPMiythSbkt6N3VhBa1e6VHRyIpJTlbE7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:42:46Z"
    mac: ENC[AES256_GCM,data:5Gjaxy2dqhgNbXso6/aMt0aVpZMwxeMgRKAO6IeB5D1fgxoPQKzWCNHtfSlI20VmSwKZKNk9wyykPrG4Nv08NFv6CAdaH2WFIFHpJKm5VzMMdtq7JmByQOY6zaLiyD/jXGRYFKOCyZ9HeTo3knNWvbx+NUREBwYjav+tVBxKJ4U=,iv:K5H7hQrrpHHLNBIhnhBBErVBZJWHhzkRjreHxGp6ltQ=,tag:Ec70vOagihxYH8AjCIL66A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: pdvd-secrets
    namespace: kube-system
stringData:
    cloudflare.apiToken: ""
sops:
    age:
        - recipient: age1m7uketvs2yftsh43p7w2eq2cqxsm9eac3xazmg6d38nrkka4la2qkjyjk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMDRrcWR2SkNXTXZrQnVX
            aWxRVnMwRVk1cTFFbGdLUC9UQk5oOVhXNDJZCnF5NmNkZUpxN0xRMzltNm5CckVM
            SU1VSnhWVkZrZjBhdHh6b2FKcVJwNjgKLS0tIFJrKzM2a1hnVnZvZDdUbEZlaE9Q
            UEhrTk10aFp2YTVqNUpRcFpDZE9ac3MK5CM0XLoOFFA/oiqKxA7ZsJh61PZd8y6f
            y6PrDZQlswNCAV6wUQL3DPMiythSbkt6N3VhBa1e6VHRyIpJTlbE7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:42:46Z"
    mac: ENC[AES256_GCM,data:5Gjaxy2dqhgNbXso6/aMt0aVpZMwxeMgRKAO6IeB5D1fgxoPQKzWCNHtfSlI20VmSwKZKNk9wyykPrG4Nv08NFv6CAdaH2WFIFHpJKm5VzMMdtq7JmByQOY6zaLiyD/jXGRYFKOCyZ9HeTo3knNWvbx+NUREBwYjav+tVBxKJ4U=,iv:K5H7hQrrpHHLNBIhnhBBErVBZJWHhzkRjreHxGp6ltQ=,tag:Ec70vOagihxYH8AjCIL66A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
