apiVersion: v1
kind: Secret
metadata:
    name: pdvd-secrets
    namespace: flux-system
stringData:
    values.yaml: ENC[AES256_GCM,data:u5J7Yw41Jjj/iGPMZnD1qnMDn7D85Vn7+J/YB4pVEa1+iYT3/rIktvznriiIMjgO1SI/QHiPuI0HyekSzbambdZYpDIDurnAKCYTY/5r7dYdIRLcpZ+XNoihqcYilLsg2JQXKdungDFZqN0bHj6HrM85vhxJoRVZDVTIHSpPcaL3cvBhL73W5+zuTbFa8Jbc/l2yn5NGTFeFwkQU+TKuYEkfB+iFQhXdOXksVBQe3QMVTjkRd5yV31JuRo6ktNA59RT2A9bR7hH5fOo9W/Rw6ZA5DhSWHkSmpi+UnOJr20VpFNZLivlgQRdgKICBYDE7id/G+zvc90YS8PktcBJsHms/lr6hJaXh90b5CcioYmMgxebPhbNSx1yltP3thIzyrQj6cKRQVeez/2irFvEmfYg2+Gzy7EiUUC0Bvy9V5U7fzLscYQrZSIXizlyUV2ORtVRkz+AJgIECvHyaFtClSwjSdR7h5g/g0e66f8S4OlYwQi1wrxfNyyaagD+sAUhXdifgrxv8Kxgef1k0izUDXw2UbxESuHgGP8enZ2VjVtBVItfc2CODFivx+/ToRqz1Wm4A3GVdQy0wCeN7yLXXHKZO9xUsB6+pScrylSweJLTLGMV6vFjnVC6LCVbqTUCRxAG0Wa6SoW3w2a3oPk9Jh7drlLawOd/7AiF28lJ+f2+MSsoYgcT0o+iNyVZEdMv7HkIGI7tzMNmzyhx4x3vYx2RY+9UCuaFk8MBUh1cyO4BZTNdMhvXQkr455bHANsGzufsKXKXBR7QoB6Cif5Qig7J/kge/kvUUO0Z1hMvg/m0w/0XE++3DtPMIBQBwRdoZdgJ+VaQbrwaWUDrPKxxUidXY13zhJfvbh/iOZ2gMNLZc6+4H3U2keQ4z3JvEFAUXd4gw/xuiWpQwA/W6GaYsmpx3HPp0o8I7/v3aCZbflc6Ugt1x1HfKcJ0zuCN6ocYs2aTjBxUWfHKs9j17yeo+I5S5jigDfUjeVmBni+QWXbXQK7mX+dBtlaWO/8o3H4PPD08yDRmHUSd/d7MlTgBvCvc17FO8mEIMguSXoDly7HouWUKdFwVVlEUWfI1gZtimZ4n7d6zOpq82cma69IzmS0QyLpIbDmlao1huS0gNhvxvnCv3oRjCFcirsWbZUZNJXE0+k7zIugUo8XGsDXl7+DhPPvq22sqzoPXdwVOfXgXj9iCFmweROR7UwExnmKw910D4xQY1mPzvXLaYz+0ba6l7zurRVRE4IiMiH12HHRyv4zlLiJsoxoLEC9rgGSvvp3txRc3vodF8KTmrcdMP/fMZMDxgHHBvqiY5UmLoKTi2TrXpu8qfano9fgxlkX7LB6Sz6gMOE5Yk+qlionCEDxJYVBMuQXgTVr/Z/mYPPMiD/8NwxBlYIWw4+6hcsEbLx9ds3XSK/oD6oKao6/7E/l8AY0bYPkWEqdWWuti4klDjw8p3+vkPichzRKO33ygSZsf9PP3NISvercoyV/fvA6bvQ6aOQ9UBqrIi01yY89TJcziFDlv2VIAgyZR1dm/K8MPIkIjUKXjK35TfYVpGVmph2UYNMCWPgUrudZ0yQDP8ifNqYBOls+HGkJTxXsF2WbWX0hAEhJd/E2be06D7ydK73pSlGKC+bOZLALaVkqAu8a4ez3G/VclQcKbbR5B9Ahd2DcEOuaSoBGwz8DsPacWva7RLFZIU+q0az9D0S/dAOg1dy0NKd2ujtn0kb/JOqNFpLzeEhDJlaSUnW0NhyZtCuUY3uwTSEqHox/n5wr25WWOyRShOWF2LjvNfXdlL+WX09srAAvLebRmNEKFOYSqAiQaoEFQYa8St/2blMex02KJzXZyuep62sWTUnorG6+c+YJnjQSX4/fs6DC+Cxgf4Ef1ff/hLw3I+S4KY47AR85kC+Jhb5l/kUanwsGUrnqpzi4VnKwyPG4EFzk1xXxqUBJz0I+Vu352wlPbraFYlPHtExBFssbmPm+3sd9NbOexeh/Ds5CQ9J/wkSPzgD8OofPa2hWtW/yegRtiOVP3SdQTMkcAm7NenxPhJws9UAu3L5iV11PDhDFQzA0Gzlk1zEIqT+biC1IwPmajWa5fWprX5mw7Ol2t9IPhK8rsDx+9N3AuAKgG78meSWTZCYzUk69OoaQqBAi7mpSsFcTlLXe7J7WbqT8eDgk6xlVu9rIggnGqCqY7db3B9q1p/4Z4AYx1P3Zwf9dIj5I8QdZjw7iyWvv0vBaSzbwnaVmMIIdrlz121ZNcRIP8wflefn2PBcEn1JXRUnmob5PjlHSsN6YL4WVVaUs6lZj3kHs7MCwbOfH/SGorcrgR0ZTHMkZnaBr3sTFJ8h0Vp9zlrAWCCqN9eKvG7+fHrtAaTum4hNj6v+ijTCsCQ3FDz3Gd5p7DeUJDP0/j7y9lOZ1tGVDh0fbK2MAL8m1s5q3U/P1ln/vGyRJfAzPvuRoIyV2EOqcV4rHNNyyzSTFZI+kbhpHst+8LXCbpK23RJy/YTcu0Iyxr6YT9hzpKQY6em2CuoTjeN+WuLNouCFboVQh9fmXeem87UE9R36qhVaIXu/YPz/bWXWRG6t35uo5rfhw4HJmZhiZU/buBPbJIqhHGZUxeEeSJsOV0UOlR7ylGaZsQfCyk0be2YmHs8HT5rB+W4MRUuiXMBsrM0jfxx5Fe9jH5Jn/a4mxu2aLuIlN3LjOIWilj3u0car/g/fnExBcFwEcN+vSvWnEppD1ceEc9qnXdDSwFoIbQbXn2vUOu5LMs4GEAJhZNjpOdA2Uq2d9+d4KHSlZxdCNPm8XE2TqNjwGsMV5Di4C6oHdAFDg3UlbA=,iv:7h7iAmPQ9UANT1KNii9wCgCg0BIQC+kMYbGjH9j3mTo=,tag:gIb/UFTMulP1nXUP7KWL8A==,type:str]
sops:
    age:
        - recipient: age1m7uketvs2yftsh43p7w2eq2cqxsm9eac3xazmg6d38nrkka4la2qkjyjk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBES2RyQnFGNVdpM3JCNzJR
            VFJnWDkzUjZpUFVjaUpYU1BKRFc3YitSU2hFCklkL1NCWTZvRGFmOFFoa3l6MDl3
            S1BheFRQdEh4eitkTVhLRWFuc01ES2sKLS0tIEF3TU1raU5QNW1qZlYxNHVQNU5B
            dVV2dXpsaUNvSDlQY2dUSCtwNnJHVWsKdhQxXL8wgWOIcNp44gNqVxi5QlLKZrRb
            n+gBJTL85jPNxZFrw/7nTCPk26Fei0F4b+LL+yvweND3plDhCELx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T17:25:58Z"
    mac: ENC[AES256_GCM,data:v3c9DxkSEOV0ZVSWLiX0xZ3a0Fxaha7Tkl88+k0Knc4PeOA4/KpMYOq/RgB3yJxz5KHHnGN0aM7IRHASHLdZMqdVxflnwHapNzZEFdXcaBIglkSzp2Xf1JZNiOU6BzHjdmcdE5YfWI/f6tul3DhHikhDzeHBZh0jwoj9lRfeqhA=,iv:f1+oSY3UHCdpsY2UGKQgDeVsagD6SABbLEdsT4JyTJw=,tag:2KArLciID/oFif7/2OThlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: pdvd-secrets
    namespace: kube-system
stringData:
    cloudflare.apiToken: ENC[AES256_GCM,data:qSBqcGUYihgz47oNhvVuUbkF3ji31Ds7j2VhN5VCwkx6wOYayQeOcw==,iv:SCS2zsj+m1LQXXaU+cJqjIKTiuNqMGV2UaiR+tM+gcI=,tag:6HZJJPz49cKwMUDnYJkZzw==,type:str]
sops:
    age:
        - recipient: age1m7uketvs2yftsh43p7w2eq2cqxsm9eac3xazmg6d38nrkka4la2qkjyjk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBES2RyQnFGNVdpM3JCNzJR
            VFJnWDkzUjZpUFVjaUpYU1BKRFc3YitSU2hFCklkL1NCWTZvRGFmOFFoa3l6MDl3
            S1BheFRQdEh4eitkTVhLRWFuc01ES2sKLS0tIEF3TU1raU5QNW1qZlYxNHVQNU5B
            dVV2dXpsaUNvSDlQY2dUSCtwNnJHVWsKdhQxXL8wgWOIcNp44gNqVxi5QlLKZrRb
            n+gBJTL85jPNxZFrw/7nTCPk26Fei0F4b+LL+yvweND3plDhCELx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T17:25:58Z"
    mac: ENC[AES256_GCM,data:v3c9DxkSEOV0ZVSWLiX0xZ3a0Fxaha7Tkl88+k0Knc4PeOA4/KpMYOq/RgB3yJxz5KHHnGN0aM7IRHASHLdZMqdVxflnwHapNzZEFdXcaBIglkSzp2Xf1JZNiOU6BzHjdmcdE5YfWI/f6tul3DhHikhDzeHBZh0jwoj9lRfeqhA=,iv:f1+oSY3UHCdpsY2UGKQgDeVsagD6SABbLEdsT4JyTJw=,tag:2KArLciID/oFif7/2OThlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
